package setup

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"github.com/ohp1x/gop1x/internal/config"
	"github.com/ohp1x/gop1x/internal/ui"
	"gopkg.in/yaml.v3"
)

type InitOptions struct {
	Force    bool
	SkipSync bool
	FromURL  string
}

type MinimalManifest struct {
	Shell   string   `yaml:"shell"`
	Presets []string `yaml:"presets"`
}

func Run(opts InitOptions) error {
	homeDir := config.Home()

	// Check if already initialized
	if _, err := os.Stat(homeDir); err == nil {
		// Directory exists - check if it's non-empty
		entries, err := os.ReadDir(homeDir)
		if err == nil && len(entries) > 0 {
			if !opts.Force {
				return fmt.Errorf("already initialized at %s\nUse --force to overwrite", homeDir)
			}
			// Backup existing
			if err := backupExisting(homeDir); err != nil {
				return fmt.Errorf("failed to backup existing: %w", err)
			}
		}
	}

	// Create directory structure
	if err := createDirectories(homeDir); err != nil {
		return fmt.Errorf("failed to create directories: %w", err)
	}

	// Write .gitignore
	if err := writeGitignore(homeDir); err != nil {
		return fmt.Errorf("failed to write .gitignore: %w", err)
	}

	// Write minimal manifest
	if err := writeManifest(homeDir); err != nil {
		return fmt.Errorf("failed to write manifest: %w", err)
	}

	// Generate init scripts
	if err := generateInitScripts(homeDir); err != nil {
		return fmt.Errorf("failed to generate init scripts: %w", err)
	}

	// Initialize git repo
	if err := initGitRepo(homeDir); err != nil {
		return fmt.Errorf("failed to initialize git repo: %w", err)
	}

	printNextSteps(homeDir)
	return nil
}

func createDirectories(homeDir string) error {
	dirs := []string{
		homeDir,
		filepath.Join(homeDir, "presets"),
		filepath.Join(homeDir, "generated"),
		filepath.Join(homeDir, "local"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create %s: %w", dir, err)
		}
	}
	return nil
}

func writeGitignore(homeDir string) error {
	gitignorePath := filepath.Join(homeDir, ".gitignore")
	content := "local/\n"
	return os.WriteFile(gitignorePath, []byte(content), 0644)
}

func writeManifest(homeDir string) error {
	manifestPath := filepath.Join(homeDir, "ohp1x.yaml")

	// Detect shell
	shell := detectShell()

	manifest := MinimalManifest{
		Shell:   shell,
		Presets: []string{},
	}

	data, err := yaml.Marshal(manifest)
	if err != nil {
		return fmt.Errorf("failed to marshal manifest: %w", err)
	}

	return os.WriteFile(manifestPath, data, 0644)
}

func detectShell() string {
	shell := os.Getenv("SHELL")
	if shell != "" {
		base := filepath.Base(shell)
		if base == "zsh" || base == "bash" || base == "fish" || base == "sh" {
			return base
		}
	}
	return "zsh" // default
}

func generateInitScripts(homeDir string) error {
	// Generate init.zsh
	zshScript := `# gop1x initialization script for Zsh
# This file is generated by gop1x init and should be sourced from ~/.zshrc

export OHP1X_HOME="${OHP1X_HOME:-$HOME/.ohp1x}"

# Add gop1x bin to PATH if not already present
if [[ ":$PATH:" != *":$OHP1X_HOME/local/bin:"* ]]; then
    export PATH="$OHP1X_HOME/local/bin:$PATH"
fi
`

	zshPath := filepath.Join(homeDir, "init.zsh")
	if err := os.WriteFile(zshPath, []byte(zshScript), 0644); err != nil {
		return fmt.Errorf("failed to write init.zsh: %w", err)
	}

	// Generate init.bash
	bashScript := `# gop1x initialization script for Bash
# This file is generated by gop1x init and should be sourced from ~/.bashrc

export OHP1X_HOME="${OHP1X_HOME:-$HOME/.ohp1x}"

# Add gop1x bin to PATH if not already present
if [[ ":$PATH:" != *":$OHP1X_HOME/local/bin:"* ]]; then
    export PATH="$OHP1X_HOME/local/bin:$PATH"
fi
`

	bashPath := filepath.Join(homeDir, "init.bash")
	if err := os.WriteFile(bashPath, []byte(bashScript), 0644); err != nil {
		return fmt.Errorf("failed to write init.bash: %w", err)
	}

	return nil
}

func initGitRepo(homeDir string) error {
	cmd := exec.Command("git", "init")
	cmd.Dir = homeDir
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to run git init: %w", err)
	}

	// Set initial git config for this repo
	cmd = exec.Command("git", "config", "user.email", "gop1x@local")
	cmd.Dir = homeDir
	_ = cmd.Run() // best effort

	cmd = exec.Command("git", "config", "user.name", "gop1x")
	cmd.Dir = homeDir
	_ = cmd.Run() // best effort

	return nil
}

func backupExisting(homeDir string) error {
	timestamp := time.Now().Format("20060102-150405")
	backupDir := homeDir + ".backup-" + timestamp
	return os.Rename(homeDir, backupDir)
}

func printNextSteps(homeDir string) {
	shell := detectShell()
	shellRC := ".zshrc"
	initFile := "init.zsh"

	if shell == "bash" {
		shellRC = ".bashrc"
		initFile = "init.bash"
	}

	ui.Ok("Initialized gop1x at " + homeDir)
	ui.Printf(`
Next steps:
1. Add to your ~/%s:
   source $HOME/.ohp1x/%s

2. Install a preset:
   gop1x add tools/fzf

3. View all presets:
   gop1x status

`, shellRC, initFile)
}
