package generate

import (
	"os"
	"path/filepath"

	"github.com/ohp1x/gop1x/internal/config"
)

const zshInit = `# gop1x shell integration for Zsh
# DO NOT EDIT — generated by gop1x generate

export OHP1X_HOME="${OHP1X_HOME:-$HOME/.ohp1x}"

# Add gop1x bin to PATH
if [[ ":$PATH:" != *":$OHP1X_HOME/local/bin:"* ]]; then
    export PATH="$OHP1X_HOME/local/bin:$PATH"
fi

# Source generated shell config
[ -f "$OHP1X_HOME/generated/shell/zshrc.zsh" ] && source "$OHP1X_HOME/generated/shell/zshrc.zsh"
[ -f "$OHP1X_HOME/local/generated/shell/zshrc.zsh" ] && source "$OHP1X_HOME/local/generated/shell/zshrc.zsh"
`

const bashInit = `# gop1x shell integration for Bash
# DO NOT EDIT — generated by gop1x generate

export OHP1X_HOME="${OHP1X_HOME:-$HOME/.ohp1x}"

# Add gop1x bin to PATH
if [[ ":$PATH:" != *":$OHP1X_HOME/local/bin:"* ]]; then
    export PATH="$OHP1X_HOME/local/bin:$PATH"
fi

# Source generated shell config
[ -f "$OHP1X_HOME/generated/shell/bashrc.sh" ] && source "$OHP1X_HOME/generated/shell/bashrc.sh"
[ -f "$OHP1X_HOME/local/generated/shell/bashrc.sh" ] && source "$OHP1X_HOME/local/generated/shell/bashrc.sh"
`

func GenerateInitScripts() error {
	home := config.Home()

	if err := os.WriteFile(filepath.Join(home, "init.zsh"), []byte(zshInit), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(home, "init.bash"), []byte(bashInit), 0644); err != nil {
		return err
	}
	return nil
}
